sudo: required
dist: trusty
language: ruby
rvm:
  - 2.5
script:
  - bundle install
  - gem build ciinabox.gemspec
  - gem install ciinabox-*.gem
  - ciinabox help
deploy:
  provider: rubygems
  api_key: "${RUBYGEMS_API_KEY}"
  gem: ciinabox
  on:
   all_branches: true
   condition: $TRAVIS_BRANCH =~ ^develop|master &&  $TRAVIS_EVENT_TYPE =~ ^push|api$ && $TRAVIS_REPO_SLUG == "ciinabox/ciinabox"
