---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ACMCertificate:
    Type: Custom::CertificateValidator
    Properties:
      ServiceToken:
        Fn::GetAtt:
        - CertificateValidatorCR
        - Arn
      AwsRegion:
        Ref: AWS::Region
      DomainName:
        Ref: DomainName
      Tags:
      - Key: Name
        Value:
          Ref: AWS::StackName
      - Key: Environment
        Value:
          Ref: EnvironmentName
      - Key: EnvironmentType
        Value:
          Ref: EnvironmentType
  LambdaRoleCertificateValidatorResource:
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: cloudwatch-logs
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:DescribeLogStreams
            - logs:DescribeLogGroups
            Resource:
            - arn:aws:logs:*:*:*
      - PolicyName: acm
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - acm:*
            - route53:*
            Resource: "*"
    Type: AWS::IAM::Role
  CertificateValidatorCR:
    Properties:
      Code:
        S3Bucket: 855280047356.ap-southeast-2.ciinabox
        S3Key: cloudformation/ciinabox-example/0.1.0/CertificateValidatorCR.acm.0.1.0.1548867245.zip
      Environment:
        Variables:
          ENVIRONMENT_NAME:
            Ref: EnvironmentName
      Handler: acm_certificate_validator_cr.handler
      MemorySize: 128
      Role:
        Fn::GetAtt:
        - LambdaRoleCertificateValidatorResource
        - Arn
      Runtime: python3.6
      Timeout: 600
    Type: AWS::Lambda::Function
  CertificateValidatorCRVersion1548867245:
    DeletionPolicy: Retain
    Properties:
      FunctionName:
        Ref: CertificateValidatorCR
      CodeSha256: 0ymKoxUSw5HGLuSO+UmAMJTdHYdPs9dPqu3aoy4KG9w=
    Type: AWS::Lambda::Version
Outputs:
  CertificateArn:
    Value:
      Ref: ACMCertificate
  CfTemplateUrl:
    Value: https://855280047356.ap-southeast-2.ciinabox.s3.amazonaws.com/cloudformation/ciinabox-example/0.1.0/acm.compiled.yaml
  CfTemplateVersion:
    Value: 0.1.0
Parameters:
  EnvironmentName:
    Type: String
    Default: dev
    NoEcho: false
  EnvironmentType:
    Type: String
    Default: development
    NoEcho: false
  DomainName:
    Type: String
    Default: ''
    NoEcho: false
  CrossAccountDNSZoneIAMRole:
    Type: String
    Default: ''
    NoEcho: false
Description: acm@latest - v0.1.0
