---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  vpc:
    Properties:
      TemplateURL: https://855280047356.ap-southeast-2.ciinabox.s3.amazonaws.com/cloudformation/ciinabox-example/0.1.0/vpc.compiled.yaml
      Parameters:
        EnvironmentType: development
        EnvironmentName: ciinabox-example
        StackOctet: '150'
        NetworkPrefix: '10'
        StackMask: '16'
        Az0:
          Fn::FindInMap:
          - Ref: AWS::AccountId
          - Ref: AWS::Region
          - Az0
        Nat0EIPAllocationId: dynamic
        Az1:
          Fn::FindInMap:
          - Ref: AWS::AccountId
          - Ref: AWS::Region
          - Az1
        Nat1EIPAllocationId: dynamic
        Az2:
          Fn::FindInMap:
          - Ref: AWS::AccountId
          - Ref: AWS::Region
          - Az2
        Nat2EIPAllocationId: dynamic
        Az3:
          Fn::FindInMap:
          - Ref: AWS::AccountId
          - Ref: AWS::Region
          - Az3
        Nat3EIPAllocationId: dynamic
        Az4:
          Fn::FindInMap:
          - Ref: AWS::AccountId
          - Ref: AWS::Region
          - Az4
        Nat4EIPAllocationId: dynamic
        DnsDomain: meetup.base2.services
        MaxNatGateways: '1'
        SingleNatGateway: 'true'
        dnszoneAddNSRecords: 'true'
        dnszoneParentIAMRole: ''
    Type: AWS::CloudFormation::Stack
  acm:
    Properties:
      TemplateURL: https://855280047356.ap-southeast-2.ciinabox.s3.amazonaws.com/cloudformation/ciinabox-example/0.1.0/acm.compiled.yaml
      Parameters:
        EnvironmentName: ciinabox-example
        EnvironmentType: development
        DomainName: "*.ciinabox-example.meetup.base2.services"
        CrossAccountDNSZoneIAMRole: ''
    Type: AWS::CloudFormation::Stack
  alb:
    Properties:
      TemplateURL: https://855280047356.ap-southeast-2.ciinabox.s3.amazonaws.com/cloudformation/ciinabox-example/0.1.0/alb.compiled.yaml
      Parameters:
        EnvironmentName: ciinabox-example
        EnvironmentType: development
        StackOctet: '150'
        DnsDomain: meetup.base2.services
        SslCertId:
          Fn::GetAtt:
          - acm
          - Outputs.CertificateArn
        SubnetPublic0:
          Fn::GetAtt:
          - vpc
          - Outputs.SubnetPublic0
        SubnetPublic1:
          Fn::GetAtt:
          - vpc
          - Outputs.SubnetPublic1
        SubnetPublic2:
          Fn::GetAtt:
          - vpc
          - Outputs.SubnetPublic2
        SubnetPublic3:
          Fn::GetAtt:
          - vpc
          - Outputs.SubnetPublic3
        SubnetPublic4:
          Fn::GetAtt:
          - vpc
          - Outputs.SubnetPublic4
        VPCId:
          Fn::GetAtt:
          - vpc
          - Outputs.VPCId
    Type: AWS::CloudFormation::Stack
  keypair:
    Properties:
      TemplateURL: https://855280047356.ap-southeast-2.ciinabox.s3.amazonaws.com/cloudformation/ciinabox-example/0.1.0/keypair.compiled.yaml
      Parameters:
        KeyPairName: ciinabox-example
        SSMParameterPath: "/ciinabox/keypair"
    Type: AWS::CloudFormation::Stack
  ecs:
    Properties:
      TemplateURL: https://855280047356.ap-southeast-2.ciinabox.s3.amazonaws.com/cloudformation/ciinabox-example/0.1.0/ecs.compiled.yaml
      Parameters:
        EnvironmentName: ciinabox-example
        EnvironmentType: development
        Ami:
          Ref: CiinaboxAmi
        InstanceType: t2.small
        AsgMin: '1'
        AsgMax: '2'
        KeyName:
          Fn::GetAtt:
          - keypair
          - Outputs.KeyPair
        DnsDomain: meetup.base2.services
        SubnetCompute0:
          Fn::GetAtt:
          - vpc
          - Outputs.SubnetCompute0
        SubnetCompute1:
          Fn::GetAtt:
          - vpc
          - Outputs.SubnetCompute1
        SubnetCompute2:
          Fn::GetAtt:
          - vpc
          - Outputs.SubnetCompute2
        SubnetCompute3:
          Fn::GetAtt:
          - vpc
          - Outputs.SubnetCompute3
        SubnetCompute4:
          Fn::GetAtt:
          - vpc
          - Outputs.SubnetCompute4
        VPCId:
          Fn::GetAtt:
          - vpc
          - Outputs.VPCId
        SecurityGroupLoadBalancer:
          Fn::GetAtt:
          - alb
          - Outputs.SecurityGroupLoadBalancer
        SecurityGroupBastion:
          Fn::GetAtt:
          - alb
          - Outputs.SecurityGroupLoadBalancer
        StackOctet: '150'
    Type: AWS::CloudFormation::Stack
  ciinaboxweb:
    Properties:
      TemplateURL: https://855280047356.ap-southeast-2.ciinabox.s3.amazonaws.com/cloudformation/ciinabox-example/0.1.0/ciinabox-web.compiled.yaml
      Parameters:
        EnvironmentName: ciinabox-example
        EnvironmentType: development
        EcsCluster:
          Fn::GetAtt:
          - ecs
          - Outputs.EcsCluster
        VPCId:
          Fn::GetAtt:
          - vpc
          - Outputs.VPCId
        LoadBalancer:
          Fn::GetAtt:
          - alb
          - Outputs.LoadBalancer
        TargetGroup:
          Fn::GetAtt:
          - alb
          - Outputs.defaultTargetGroup
        Listener:
          Fn::GetAtt:
          - alb
          - Outputs.httpsListener
        DnsDomain: meetup.base2.services
        DesiredCount: '1'
        MinimumHealthyPercent: '0'
        MaximumPercent: '100'
        EnableScaling: 'false'
        Version:
          Ref: ciinaboxwebVersion
    Type: AWS::CloudFormation::Stack
Outputs:
  CfTemplateUrl:
    Value: https://855280047356.ap-southeast-2.ciinabox.s3.amazonaws.com/cloudformation/ciinabox-example/0.1.0/ciinabox-example.compiled.yaml
  CfTemplateVersion:
    Value: 0.1.0
Parameters:
  CiinaboxAmi:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: "/aws/service/ecs/optimized-ami/amazon-linux/recommended/image_id"
    NoEcho: false
  ciinaboxwebVersion:
    Type: String
    Default: latest
    NoEcho: false
Description: ciinabox-example@latest - v0.1.0
Mappings:
  AccountId:
    '855280047356':
      Dummy: '1'
  '855280047356':
    ap-south-1:
      Az0: ap-south-1a
      Az1: ap-south-1b
      Az2: false
      Az3: false
      Az4: false
    eu-west-3:
      Az0: eu-west-3a
      Az1: eu-west-3b
      Az2: eu-west-3c
      Az3: false
      Az4: false
    eu-north-1:
      Az0: eu-north-1a
      Az1: eu-north-1b
      Az2: eu-north-1c
      Az3: false
      Az4: false
    eu-west-2:
      Az0: eu-west-2a
      Az1: eu-west-2b
      Az2: eu-west-2c
      Az3: false
      Az4: false
    eu-west-1:
      Az0: eu-west-1a
      Az1: eu-west-1b
      Az2: eu-west-1c
      Az3: false
      Az4: false
    ap-northeast-2:
      Az0: ap-northeast-2a
      Az1: ap-northeast-2c
      Az2: false
      Az3: false
      Az4: false
    ap-northeast-1:
      Az0: ap-northeast-1a
      Az1: ap-northeast-1c
      Az2: ap-northeast-1d
      Az3: false
      Az4: false
    sa-east-1:
      Az0: sa-east-1a
      Az1: sa-east-1c
      Az2: false
      Az3: false
      Az4: false
    ca-central-1:
      Az0: ca-central-1a
      Az1: ca-central-1b
      Az2: false
      Az3: false
      Az4: false
    ap-southeast-1:
      Az0: ap-southeast-1a
      Az1: ap-southeast-1b
      Az2: ap-southeast-1c
      Az3: false
      Az4: false
    ap-southeast-2:
      Az0: ap-southeast-2a
      Az1: ap-southeast-2b
      Az2: ap-southeast-2c
      Az3: false
      Az4: false
    eu-central-1:
      Az0: eu-central-1a
      Az1: eu-central-1b
      Az2: eu-central-1c
      Az3: false
      Az4: false
    us-east-1:
      Az0: us-east-1a
      Az1: us-east-1b
      Az2: us-east-1c
      Az3: us-east-1d
      Az4: us-east-1e
      Az5: us-east-1f
    us-east-2:
      Az0: us-east-2a
      Az1: us-east-2b
      Az2: us-east-2c
      Az3: false
      Az4: false
    us-west-1:
      Az0: us-west-1a
      Az1: us-west-1b
      Az2: false
      Az3: false
      Az4: false
    us-west-2:
      Az0: us-west-2a
      Az1: us-west-2b
      Az2: us-west-2c
      Az3: false
      Az4: false
