---
AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  IsScalingEnabled:
    Fn::Equals:
    - Ref: EnableScaling
    - 'true'
Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Ref: AWS::StackName
      RetentionInDays: '7'
  TaskRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ecs-tasks.amazonaws.com
          Action:
          - sts:AssumeRole
        - Effect: Allow
          Principal:
            Service:
            - ssm.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: ssm
        PolicyDocument:
          Statement:
          - Sid: ssm
            Action:
            - ssm:GetParameters*
            Resource:
            - Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:ciinabox
            - Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:ciinabox/*
            Effect: Allow
    Type: AWS::IAM::Role
  ExecutionRole:
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
    Type: AWS::IAM::Role
  Task:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
      - Name: ciinabox
        Image:
          Fn::Join:
          - ''
          - - ''
            - nginx
            - ":"
            - Ref: Version
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group:
              Ref: LogGroup
            awslogs-region:
              Ref: AWS::Region
            awslogs-stream-prefix: ciinabox
        Environment:
        - Name: ENVIRONMENT_NAME
          Value:
            Fn::Sub: "${EnvironmentName}"
        - Name: AWS_REGION
          Value:
            Fn::Sub: "${AWS::Region}"
        PortMappings:
        - ContainerPort: 80
      Cpu: 128
      Memory: 128
      TaskRoleArn:
        Ref: TaskRole
      ExecutionRoleArn:
        Ref: ExecutionRole
  Role:
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: ecs.amazonaws.com
          Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceRole
    Type: AWS::IAM::Role
  Service:
    Properties:
      Cluster:
        Ref: EcsCluster
      HealthCheckGracePeriodSeconds: 20
      DesiredCount:
        Ref: DesiredCount
      DeploymentConfiguration:
        MinimumHealthyPercent:
          Ref: MinimumHealthyPercent
        MaximumPercent:
          Ref: MaximumPercent
      TaskDefinition:
        Ref: Task
      Role:
        Ref: Role
      LoadBalancers:
      - ContainerName: ciinabox
        ContainerPort: 80
        TargetGroupArn:
          Ref: TargetGroup
    Type: AWS::ECS::Service
Outputs:
  CfTemplateUrl:
    Value: https://855280047356.ap-southeast-2.ciinabox.s3.amazonaws.com/cloudformation/ciinabox-example/0.1.0/ecs-service.compiled.yaml
  CfTemplateVersion:
    Value: 0.1.0
Parameters:
  EnvironmentName:
    Type: String
    Default: dev
    NoEcho: false
  EnvironmentType:
    Type: String
    Default: development
    NoEcho: false
    AllowedValues:
    - development
    - production
  EcsCluster:
    Type: String
    Default: ''
    NoEcho: false
  VPCId:
    Type: AWS::EC2::VPC::Id
    Default: ''
    NoEcho: false
  LoadBalancer:
    Type: String
    Default: ''
    NoEcho: false
  TargetGroup:
    Type: String
    Default: ''
    NoEcho: false
  Listener:
    Type: String
    Default: ''
    NoEcho: false
  DnsDomain:
    Type: String
    Default: ''
    NoEcho: false
  DesiredCount:
    Type: String
    Default: '1'
    NoEcho: false
  MinimumHealthyPercent:
    Type: String
    Default: '100'
    NoEcho: false
  MaximumPercent:
    Type: String
    Default: '200'
    NoEcho: false
  EnableScaling:
    Type: String
    Default: 'false'
    NoEcho: false
    AllowedValues:
    - 'true'
    - 'false'
  Version:
    Type: String
    Default: latest
    NoEcho: false
Description: ecs-service - ciinabox-web - 0.1.0
