---
maximum_availability_zones: 5
manage_ns_records: true
stack_octet: 150
ecs_instance_type: t2.small
ip_blocks:
  ciinabox:
  - 127.0.0.1/32
  internal:
  - stack
  webhooks:
  - 104.192.143.192/28
  - 104.192.143.208/28
  - 104.192.136.0/21
  - 34.198.203.127/32
  - 34.198.178.64/32
  - 34.198.32.85/32
components:
  vpc:
    config:
      manage_ns_records: true
      subnets:
        vpc_public:
          allocation: 0
          name: Public
          type: public
        compute:
          allocation: 1
          name: Compute
          type: private
  alb:
    config:
      records:
      - "*"
      securityGroups:
        loadbalancer:
        - rules:
          - IpProtocol: tcp
            FromPort: 443
            ToPort: 443
          - IpProtocol: tcp
            FromPort: 80
            ToPort: 80
          ips:
          - ciinabox
          - internal
          - webhooks
      listeners:
        http:
          port: 80
          protocol: http
          default_targetgroup: default
        https:
          port: 443
          protocol: https
          default_targetgroup: default
          ssl_policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
  ciinabox-web:
    config:
      health_check_grace_period: 20
      cpu: 128
      memory: 128
      task_definition:
        ciinabox:
          image: nginx
          tag_param: Version
          tag_param_default: latest
          env_vars:
            ENVIRONMENT_NAME:
              Fn::Sub: "${EnvironmentName}"
            AWS_REGION:
              Fn::Sub: "${AWS::Region}"
          ports:
          - 80
      targetgroup:
        name: default
        container: ciinabox
        port: 80
      iam_policies:
        ssm:
          action:
          - ssm:GetParameters*
          resource:
          - Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:ciinabox
          - Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:ciinabox/*
config_export:
  global:
  - maximum_availability_zones
  - ip_blocks
ciinabox_name: example
ciinabox_version: 0.1.0
aws_account: 855280047356
aws_region: ap-southeast-2
source_bucket: 855280047356.ap-southeast-2.ciinabox
dns_zone: meetup.base2.services
component_version: 0.1.0
component_name: ciinabox-example
template_name: ciinabox-example
template_version: latest
mappings:
  AccountId:
    855280047356:
      Dummy: '1'
  '855280047356':
    ap-south-1:
      Az0: ap-south-1a
      Az1: ap-south-1b
      Az2: false
      Az3: false
      Az4: false
    eu-west-3:
      Az0: eu-west-3a
      Az1: eu-west-3b
      Az2: eu-west-3c
      Az3: false
      Az4: false
    eu-north-1:
      Az0: eu-north-1a
      Az1: eu-north-1b
      Az2: eu-north-1c
      Az3: false
      Az4: false
    eu-west-2:
      Az0: eu-west-2a
      Az1: eu-west-2b
      Az2: eu-west-2c
      Az3: false
      Az4: false
    eu-west-1:
      Az0: eu-west-1a
      Az1: eu-west-1b
      Az2: eu-west-1c
      Az3: false
      Az4: false
    ap-northeast-2:
      Az0: ap-northeast-2a
      Az1: ap-northeast-2c
      Az2: false
      Az3: false
      Az4: false
    ap-northeast-1:
      Az0: ap-northeast-1a
      Az1: ap-northeast-1c
      Az2: ap-northeast-1d
      Az3: false
      Az4: false
    sa-east-1:
      Az0: sa-east-1a
      Az1: sa-east-1c
      Az2: false
      Az3: false
      Az4: false
    ca-central-1:
      Az0: ca-central-1a
      Az1: ca-central-1b
      Az2: false
      Az3: false
      Az4: false
    ap-southeast-1:
      Az0: ap-southeast-1a
      Az1: ap-southeast-1b
      Az2: ap-southeast-1c
      Az3: false
      Az4: false
    ap-southeast-2:
      Az0: ap-southeast-2a
      Az1: ap-southeast-2b
      Az2: ap-southeast-2c
      Az3: false
      Az4: false
    eu-central-1:
      Az0: eu-central-1a
      Az1: eu-central-1b
      Az2: eu-central-1c
      Az3: false
      Az4: false
    us-east-1:
      Az0: us-east-1a
      Az1: us-east-1b
      Az2: us-east-1c
      Az3: us-east-1d
      Az4: us-east-1e
      Az5: us-east-1f
    us-east-2:
      Az0: us-east-2a
      Az1: us-east-2b
      Az2: us-east-2c
      Az3: false
      Az4: false
    us-west-1:
      Az0: us-west-1a
      Az1: us-west-1b
      Az2: false
      Az3: false
      Az4: false
    us-west-2:
      Az0: us-west-2a
      Az1: us-west-2b
      Az2: us-west-2c
      Az3: false
      Az4: false
description: ciinabox-example@latest - v0.1.0
