---
component_version: 0.1.0
maximum_availability_zones: 5
log_retention: 7
nested_component: true
health_check_grace_period: 20
cpu: 128
memory: 128
task_definition:
  ciinabox:
    image: nginx
    tag_param: Version
    tag_param_default: latest
    env_vars:
      ENVIRONMENT_NAME:
        Fn::Sub: "${EnvironmentName}"
      AWS_REGION:
        Fn::Sub: "${AWS::Region}"
    ports:
    - 80
targetgroup:
  name: default
  container: ciinabox
  port: 80
iam_policies:
  ssm:
    action:
    - ssm:GetParameters*
    resource:
    - Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:ciinabox
    - Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:ciinabox/*
ip_blocks:
  ciinabox:
  - 127.0.0.1/32
  internal:
  - stack
  webhooks:
  - 104.192.143.192/28
  - 104.192.143.208/28
  - 104.192.136.0/21
  - 34.198.203.127/32
  - 34.198.178.64/32
  - 34.198.32.85/32
component_name: ciinabox-web
template_name: ecs-service
template_version: 1.7.2
description: ecs-service - ciinabox-web - 0.1.0
