---
keypair_custom_resources:
  custom_policies:
    lambda:
      action:
      - lambda:InvokeFunction
      resource:
        Fn::Sub: arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${AWS::StackName}-KeyPairCR*
    keypair:
      action:
      - ec2:CreateKeyPair
      - ec2:DeleteKeyPair
      - ssm:PutParameter
      - ssm:DeleteParameter
      resource: "*"
  roles:
    KeyPairResource:
      policies_inline:
      - cloudwatch-logs
      - keypair
      - lambda
  functions:
    KeyPairCR:
      code: cr_keypair.py
      handler: cr_keypair.handler
      runtime: python3.6
      timeout: 600
      role: KeyPairResource
nested_component: true
maximum_availability_zones: 5
ip_blocks:
  ciinabox:
  - 127.0.0.1/32
  internal:
  - stack
  webhooks:
  - 104.192.143.192/28
  - 104.192.143.208/28
  - 104.192.136.0/21
  - 34.198.203.127/32
  - 34.198.178.64/32
  - 34.198.32.85/32
component_version: 0.1.0
component_name: keypair
template_name: keypair
template_version: latest
description: keypair@latest - v0.1.0
lambda_metadata:
  path:
    KeyPairCR: KeyPairCR.keypair.0.1.0.1548867245.zip
  sha256:
    KeyPairCR: Xy8qOVipaZpJVW0JbMLglofibZzedDrT08l7P42I8qc=
  version:
    KeyPairCR: '1548867245'
