---
maximum_availability_zones: 5
loadbalancer_type: application
loadbalancer_scheme: public
loadbalancer_attributes:
  idle_timeout.timeout_seconds: 120
loadbalancer_tags:
  Name: public
ip_blocks:
  public:
  - 0.0.0.0/0
  internal:
  - stack
  ciinabox:
  - 127.0.0.1/32
  webhooks:
  - 104.192.143.192/28
  - 104.192.143.208/28
  - 104.192.136.0/21
  - 34.198.203.127/32
  - 34.198.178.64/32
  - 34.198.32.85/32
targetgroups:
  default:
    protocol: http
    port: 80
    tags:
      Name: Default-HTTP
listeners:
  http:
    port: 80
    protocol: http
    default_targetgroup: default
  https:
    port: 443
    protocol: https
    default_targetgroup: default
    ssl_policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
securityGroups:
  loadbalancer:
  - rules:
    - IpProtocol: tcp
      FromPort: 443
      ToPort: 443
    - IpProtocol: tcp
      FromPort: 80
      ToPort: 80
    ips:
    - ciinabox
    - internal
    - webhooks
nested_component: true
records:
- "*"
component_version: 0.1.0
component_name: alb
template_name: loadbalancer
template_version: latest
description: alb - v0.1.0 (loadbalancer@latest)
