---
maximum_availability_zones: 5
component_version: 0.1.0
subnets:
  vpc_public:
    allocation: 0
    name: Public
    type: public
  compute:
    allocation: 1
    name: Compute
    type: private
  persistence:
    allocation: 2
    name: Persistence
    type: private
  cache:
    allocation: 3
    name: Cache
    type: private
enable_transit_vpc: false
manage_ns_records: true
public_acl_rules:
  inbound:
  - number: 100
    from: 22
  - number: 200
    from: 80
  - number: 300
    from: 443
  - number: 400
    from: 1024
    to: 65535
  - number: 500
    protocol: 17
    from: 1024
    to: 65535
  outbound:
  - number: 100
    protocol: -1
    from: 1024
    to: 65535
securityGroups:
  ops:
  - rules:
    - IpProtocol: tcp
      FromPort: 22
      ToPort: 22
    - IpProtocol: tcp
      FromPort: 80
      ToPort: 80
    - IpProtocol: tcp
      FromPort: 3389
      ToPort: 3389
    ips:
    - ops
  dev:
  - rules:
    - IpProtocol: tcp
      FromPort: 22
      ToPort: 22
    - IpProtocol: tcp
      FromPort: 80
      ToPort: 80
    - IpProtocol: tcp
      FromPort: 3389
      ToPort: 3389
    ips:
    - dev
  backplane:
  - rules:
    - IpProtocol: tcp
      FromPort: 22
      ToPort: 22
    - IpProtocol: tcp
      FromPort: 80
      ToPort: 80
    - IpProtocol: tcp
      FromPort: 443
      ToPort: 443
    - IpProtocol: tcp
      FromPort: 25
      ToPort: 25
    - IpProtocol: tcp
      FromPort: 3389
      ToPort: 3389
    - IpProtocol: udp
      FromPort: 123
      ToPort: 123
    - IpProtocol: udp
      FromPort: 123
      ToPort: 123
    ips:
    - stack
  - rules:
    - IpProtocol: tcp
      FromPort: 5666
      ToPort: 5666
    ips:
    - monitoring
ip_blocks:
  public:
  - 0.0.0.0/0
  ops:
  - 169.254.100.100/32
  dev:
  - 169.254.100.100/32
  monitoring:
  - 169.254.100.100/32
  ciinabox:
  - 127.0.0.1/32
  internal:
  - stack
  webhooks:
  - 104.192.143.192/28
  - 104.192.143.208/28
  - 104.192.136.0/21
  - 34.198.203.127/32
  - 34.198.178.64/32
  - 34.198.32.85/32
managed_accounts:
  ops:
    local: true
config_export:
  global:
  - maximum_availability_zones
lib_export:
  global:
    cfndsl:
    - az
nested_component: true
component_name: vpc
template_name: vpc
template_version: latest
description: Highlander VPC component 0.1.0
